### ISSUE TITLE
Unable to add a new host group - Error

### ISSUE THREAD

**Issue by tachtler** [Thomas-Gelf/icingaweb2-module-fileshipper#2]
Hi,

when I try to **add** a new **host group** with icinga2-director, following error occurs:
(I have installed the latest version from github (master).)
```
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1133): Icinga\Module\Director\Objects\IcingaObject->assertCustomVarsSupport()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(51): Icinga\Module\Director\Objects\IcingaObject->vars()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(263): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->setValues(Array, 'var_')
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(566): Icinga\Module\Director\Web\Form\DirectorObjectForm->handleCustomVars(Object(Icinga\Module\Director\Objects\IcingaHostGroup), Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(430): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(437): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(304): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(205): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#8 /usr/share/php/Zend/Controller/Action.php(516): Icinga\Module\Director\Web\Controller\ObjectController->addAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#10 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}
```
For any other information about my setup, please tell me what information I have to give to you!

Thank you!
Klaus.

**Comment by tachtler** [comment]
Sorry wrong module!
